default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  encoding: unicode

development:
  <<: *default
  database: ads_microservice_development

test:
  <<: *default
  database: ads_microservice_test
  max_connection: 1
