name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          createdb -U postgres -h localhost auth_microservice_test
          bin/rake db:migrate
        env:
          RACK_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: Run RSpec
        run: bundle exec rspec ./spec
        env:
          RACK_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
